---
title: "Figure 5 Epigenomic Approaches to Identify Master Transcription Factors Regulating Mouse Cardiac Development"
output:
  html_document:
    df_print: paged
---

Library Packages
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
suppressPackageStartupMessages(library(ggplot2)) # CRAN v3.3.5
suppressPackageStartupMessages(library(ggsci)) # CRAN v2.9
suppressPackageStartupMessages(library(clusterProfiler)) # Bioconductor v4.0.5
suppressPackageStartupMessages(library(org.Mm.eg.db)) # Bioconductor v3.13.0
suppressPackageStartupMessages(library(magrittr)) # CRAN v2.0.1
suppressPackageStartupMessages(library(ggExtra)) # CRAN v0.9
suppressPackageStartupMessages(library(ggpubr)) # CRAN v0.4.0
suppressPackageStartupMessages(library(ggrepel)) # CRAN v0.9.1

rm(list = ls(all.names = TRUE))
gc()
```

Figure 5B
Cytohubba output were saved in 'Cytohubba Result.csv'
Calculate rank of significance
```{r echo=TRUE}
hub <- read.csv("./Cytohubba Result.csv")
order <- data.frame(hub$node_name) # calculate rank of each indicater
for (i in 2:12) {
  temp <- rank(-hub[,i])
  order <- cbind(order,temp)
}
names(order) <- colnames(hub)
order <- cbind(order,Mean = rank(rowMeans(order[,2:12]))) # calculate mean
order <- order[order(order$Mean,decreasing = FALSE),]
```

Figure 5C
a. Proportion of HDSTFs
```{r echo=TRUE}
hdstf <- read.csv("./Annotations of TFs/hdstf.csv") # Annotations of Heart-Development-Significant-TFs
tp <- hdstf[order(hdstf$Rank),1:3]
tp <- cbind(tp,Group = c(rep("Rank I",nrow(tp[tp$Rank <= 200,])),
                         rep("Rank II",nrow(tp[tp$Rank > 200 & tp$Rank <= 400,])),
                         rep("Rank III",nrow(tp[tp$Rank > 400,]))))
tp$Group <- factor(tp$Group,ordered = TRUE,levels = c("Rank I","Rank II","Rank III"))
# Fisher Exact Tests
tp <- xtabs(~Group+Involved.in.cardiac.development,data = tp)
fisher.test(tp)
# Plottig
tmp <- as.data.frame(prop.table(tp,1))
tp <- as.data.frame(tp)
tp <- cbind(tp,Prop = tmp$Freq,Pos = tmp$Freq)
tp[tp$Pos > 0.5,4] <- rep(1,(length(tp[tp$Pos > 0.5,4])))

ggplot(tp[tp$Involved.in.cardiac.development == TRUE,],aes(fill = Group,y = Prop,x = Group)) +
  geom_bar(position = "stack",stat = "identity",width = 0.7,alpha = 0.7,color = "#666666",lwd = 1.3) +
  geom_text(aes(label = round(Prop,3),y = Pos - 0.05),color = "White",vjust = 0,size = 7) +
  annotate("text",label = "Fisher's Exact Test P = 3.75e-4",x = Inf,y = Inf,hjust = 1.1,vjust = 1.5,size = 7) +
  theme_classic() +
  theme(panel.background = element_rect(fill = NA,colour = "Black",size = 1,linetype = 1),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        plot.title = element_text(size = 20,hjust = 0.5)) +
  scale_fill_npg() +
  labs(x = "Grouped Rank of Significance",y = "Proportion")
```

b. Comparison of early-stage development
```{r echo=TRUE}
load("../SourceData/omic_data.Rds")
# Compile ranked TF list
hub <- read.csv("./Cytohubba Result.csv")
order <- data.frame(hub$node_name) # calculate rank of each indicater
for (i in 2:12) {
  temp <- rank(-hub[,i])
  order <- cbind(order,temp)
}
names(order) <- colnames(hub)
order <- cbind(order,Mean = rank(rowMeans(order[,2:12]))) # calculate mean
order <- order[order(order$Mean,decreasing = FALSE),]

tf <- order %>% 
  .[,c(1,13)]
names(tf) <- c("Gene_symbol","Rank")
# Annotate Genes
trs <- data.frame(mmu_heart_trs[,1])
for (i in seq(2,31,3)) {
  trs <- cbind(trs,rowMeans(mmu_heart_trs[,i:(i+2)]))  
};rm(i)
temp_ensemble <- substr(trs[,1],1,18)
geneinfo <- select(org.Mm.eg.db,keys = temp_ensemble,columns = c("SYMBOL","ENTREZID"),keytype = "ENSEMBL")
geneinfo <- geneinfo[!duplicated(geneinfo[,1]),]
trs <- cbind(geneinfo,trs[,-1]);rm(temp_ensemble,geneinfo)
trs <- trs[!duplicated(trs[,2]),]
trs <- trs[rowSums(trs[,4:13]) > 0,]
names(trs)[c(2,4:13)] <- c("Gene_symbol","E10.5","E12.5","E14.5","E16.5","E18.5","P1","1W","2W","4W","8W")
# Compile expression list
tf.exp <- merge(tf,trs)
tf.exp <- cbind(tf.exp[,1:2],Exp = rowMeans(tf.exp[,5:7]),Exp_Rank = rank(rowMeans(tf.exp[,5:7])))
# Plotting
tp <- tf.exp[order(tf.exp$Rank),]
tp <- tp[!(tp$Exp > quantile(tp$Exp,0.95)),]
tp <- cbind(tp,Group = c(rep("Rank I",nrow(tp[tp$Rank <= 200,])),
                         rep("Rank II",nrow(tp[tp$Rank > 200 & tp$Rank <= 400,])),
                         rep("Rank III",nrow(tp[tp$Rank > 400,]))))
tp$Group <- factor(tp$Group,ordered = TRUE,levels = c("Rank I","Rank II","Rank III"))

my_comparisons <- list(c("Rank I","Rank II"), c("Rank I","Rank III"), c("Rank II","Rank III"))
ggplot(tp,aes(x = Group,y = Exp,fill = Group)) +
  # geom_violin() +
  geom_boxplot(width = 0.7,color = "#666666",alpha = 0.7,outlier.alpha = 0,position = "dodge",lwd = 1.3) +
  theme_classic() +
  theme(panel.background = element_rect(fill = NA,colour = "Black",size = 1,linetype = 1),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        plot.title = element_text(size = 20,hjust = 0.5)) +
  scale_fill_npg() +
  stat_compare_means(comparisons = my_comparisons,label = "p.signif",size = 7) +
  stat_compare_means(label.y = 50,size = 7) +
  scale_x_discrete(expand = c(1.3,0)) + 
  labs(x = "Rank of Significance",y = "Heart Expression in Early Stage")
```

c. Comparison of pLI score
```{r}
# Compile ranked TF list
hub <- read.csv("./Cytohubba Result.csv")
order <- data.frame(hub$node_name) # calculate rank of each indicater
for (i in 2:12) {
  temp <- rank(-hub[,i])
  order <- cbind(order,temp)
}
names(order) <- colnames(hub)
order <- cbind(order,Mean = rank(rowMeans(order[,2:12]))) # calculate mean
order <- order[order(order$Mean,decreasing = FALSE),]

tf <- order %>% 
  .[,c(1,13)]
names(tf) <- c("Gene_symbol","Rank")
# Compile pLI score
pLI <- read.csv("./Annotations of TFs/pLI score.csv") # pLI score of all genes
pLI$Gene_symbol <- paste(substr(pLI$Gene_symbol,1,1),
                         tolower(substr(pLI$Gene_symbol,2,nchar(pLI$Gene_symbol))),
                         sep = "")
tf.pl <- merge(tf,pLI[,c(1,6,9,11)])
# Plotting
tp <- tf.pl[!tf.pl$pLI_score == ".",]
tp$pLI_score <- as.numeric(tp$pLI_score)
tp <- tp[order(tp$Rank),]
tp <- cbind(tp,Group = c(rep("Rank I",nrow(tp[tp$Rank <= 200,])),
                         rep("Rank II",nrow(tp[tp$Rank > 200 & tp$Rank <= 400,])),
                         rep("Rank III",nrow(tp[tp$Rank > 400,]))))
tp$Group <- factor(tp$Group,ordered = TRUE,levels = c("Rank I","Rank II","Rank III"))

my_comparisons <- list(c("Rank I","Rank II"), c("Rank I","Rank III"), c("Rank II","Rank III"))
ggplot(tp,aes(x = Group,y = pLI_score,fill = Group)) +
  # geom_violin() +
  geom_boxplot(width = 0.7,color = "#666666",alpha = 0.7,position = "dodge",lwd = 1.3) +
  theme_classic() +
  theme(panel.background = element_rect(fill = NA,colour = "Black",size = 1,linetype = 1),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        plot.title = element_text(size = 20,hjust = 0.5)) +
  scale_fill_npg() +
  stat_compare_means(comparisons = my_comparisons,label = "p.signif",size = 7) +
  stat_compare_means(label.y = 1.5,size = 7) +
  scale_x_discrete(expand = c(1.3,0)) + 
  labs(x = "Rank of Significance",y = "pLI Score")
```

Figure 5D
Compile data
```{r echo=TRUE}
load("../SourceData/omic_data.Rds")
# Compile ranked TF list
hub <- read.csv("./Cytohubba Result.csv")
order <- data.frame(hub$node_name) # calculate rank of each indicater
for (i in 2:12) {
  temp <- rank(-hub[,i])
  order <- cbind(order,temp)
}
names(order) <- colnames(hub)
order <- cbind(order,Mean = rank(rowMeans(order[,2:12]))) # calculate mean
order <- order[order(order$Mean,decreasing = FALSE),]

tf <- order %>% 
  .[,c(1,13)]
names(tf) <- c("Gene_symbol","Rank")
# Compile expression list
trs <- data.frame(mmu_heart_trs[,1])
for (i in seq(2,31,3)) {
  trs <- cbind(trs,rowMeans(mmu_heart_trs[,i:(i+2)]))  
};rm(i)
temp_ensemble <- substr(trs[,1],1,18)
geneinfo <- select(org.Mm.eg.db,keys = temp_ensemble,columns = c("SYMBOL","ENTREZID"),keytype = "ENSEMBL")
geneinfo <- geneinfo[!duplicated(geneinfo[,1]),]
trs <- cbind(geneinfo,trs[,-1]);rm(temp_ensemble,geneinfo)
trs <- trs[!duplicated(trs[,2]),]
trs <- trs[rowSums(trs[,4:13]) > 0,]
names(trs)[c(2,4:13)] <- c("Gene_symbol","E10.5","E12.5","E14.5","E16.5","E18.5","P1","1W","2W","4W","8W")

tf.exp <- merge(tf,trs)
tf.exp <- cbind(tf.exp[,1:2],Exp = rowMeans(tf.exp[,5:7]),Exp_Rank = rank(rowMeans(tf.exp[,5:7])))
# Compile pLI score
pLI <- read.csv("./Annotations of TFs/pLI score.csv") # pLI score of all genes
pLI$Gene_symbol <- paste(substr(pLI$Gene_symbol,1,1),
                         tolower(substr(pLI$Gene_symbol,2,nchar(pLI$Gene_symbol))),
                         sep = "")
tf.pl <- merge(tf,pLI[,c(1,6,9,11)])
```

Plotting of main (All)
```{r echo=TRUE}
tp <- merge(tf.pl,tf.exp) # Merge pLI and Exp
tp <- tp[!tp$pLI_score == ".",]
tp$pLI_score <- as.numeric(tp$pLI_score)
tp <- tp[order(tp$Rank),]
tp <- cbind(tp,Group = c(rep("Top 200",200),rep("> 200",nrow(tp)-200)))
tp$Group <- factor(tp$Group,ordered = TRUE,levels = c("Top 200","> 200"))

p <- ggplot(tp,aes(x = Exp_Rank,y = pLI_score,fill = Group,alpha = Group)) + 
  geom_point(shape = 21,color = "Black",size = 15) +
  geom_text_repel(data = tp[(tp$Rank <= 200) & (tp$pLI_score > 0.9) & (tp$Exp_Rank > 422),],
                  aes(label = Gene_symbol),size = 5,max.overlaps = 200) +
  # geom_text(aes(label = Gene_symbol),size = 4,hjust = 1.5) +
  theme_classic() +
  theme(panel.background = element_rect(fill = NA,colour = "Black",size = 1,linetype = 1),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 20),
        plot.title = element_text(size = 20,hjust = 0.5)) +
  scale_alpha_manual(values = c(0.8,0.3)) +
  scale_fill_manual(values = c("firebrick","ivory")) +
  labs(x = "Heart Expression in Early Stage (Rank)",y = "pLI Score",fill = "Rank of Significance")
ggMarginal(p,type = "histogram")
```

Plotting of histogram (Distribution of Top200)
```{r echo=TRUE}
tp <- merge(tf.pl,tf.exp) # Merge pLI and Exp
tp <- tp[!tp$pLI_score == ".",]
tp$pLI_score <- as.numeric(tp$pLI_score)
tp <- tp[order(tp$Rank),]
tp <- cbind(tp,Group = c(rep("Top 200",200),rep("> 200",nrow(tp)-200)))
tp$Group <- factor(tp$Group,ordered = TRUE,levels = c("Top 200","> 200"))
tp <- tp[tp$Group == "Top 200",]

p <- ggplot(tp,aes(x = Exp_Rank,y = pLI_score,fill = Group,alpha = Group)) + 
  geom_point(shape = 21,color = "Black",size = 15) +
  geom_text_repel(data = tp[(tp$Rank <= 200) & (tp$pLI_score > 0.9) & (tp$Exp_Rank > 422),],
                  aes(label = Gene_symbol),size = 5,max.overlaps = 200) +
  # geom_text(aes(label = Gene_symbol),size = 4,hjust = 1.5) +
  theme_classic() +
  theme(panel.background = element_rect(fill = NA,colour = "Black",size = 1,linetype = 1),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 20),
        plot.title = element_text(size = 20,hjust = 0.5)) +
  scale_alpha_manual(values = c(0.8,0.3)) +
  scale_fill_manual(values = c("firebrick","ivory")) +
  labs(x = "Heart Expression in Early Stage (Rank)",y = "pLI Score",fill = "Rank of Significance")
ggMarginal(p,type = "histogram")
```
